### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by egillespie** [egillespie/codelab-sinatra-helper-methods#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://thawing-spire-62205.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-helper-methods/1) criteria:

- [x] Define and use a method called `pluralize` in your app. It should take two parameters: `singular_name` and `count`. `pluralize('cat', 5)` should return `'5 cats'`, `pluralize('cat', 1)` should return `'1 cat'`, and `pluralize('cat', 0)` should return `'0 cats'`.
- [x] Define and use a method called `use_google_font` in your app. It should take a single parameter: `font`. It should return the `link` element to include the font and a `style` element that applies the font to the body. Example usage would be `use_google_font('Open Sans')`. This one requires you know how to [customize the fonts in a webpage](http://lansingcodelab.com/lessons/css-font-families/1), so complete or review that lesson if you need to.
- [x] Define and use a method called `icon_button` in your app. It should take 3 parameters: `icon`, `type` (with a default value of `'default'`), and `message`, with a default value of `''`. That means the only required parameter is `icon`. It should return a button with an icon, similar to the [example in the Bootstrap docs](http://getbootstrap.com/components/#glyphicons-examples). Note that Bootstrap must be correctly included in your app for this to work.

**Comment by chrisvfritz** [comment]
Nice callback with the pluralizations! :smile_cat: :smile_cat: :smile_cat: Everything looks really good here, so I'll give you the :shipit:! In case you're curious though, here's some extra info I thought you might enjoy. __None of it is a suggestion__, but may be helpful as you get to know Ruby, since you're already an experienced programmer.

### More advanced pluralization

People need to pluralize words so often that Rails has [its own `pluralize` helper](https://github.com/rails/rails/blob/861b70e92f4a1fc0e465ffcf2ee62680519c8f6f/activesupport/lib/active_support/inflector/methods.rb#L31-L33). What you have is a fantastic start, but if you're curious how you'd handle all the irregular pluralizations in English, you can source-dive to see how they do it. :smiley: 

Here are some of the advanced pluralizations they handle:

``` ruby
'bacterium'.pluralize
=> "bacteria"
'money'.pluralize
=> "money"
'person'.pluralize
=> "people"
fairy'.pluralize
=> "fairies"
```

You may also notice that Rails adds `pluralize` as an instance method on the `String` class, so that it's even more convenient!

### Encoding strings for URLs

What you have works, since I believe all Google fonts contain only alphanumeric characters and spaces (and modern browsers are very good at treating the spaces as `%20`). But in the case that you wanted to _make sure_ the name provided was properly escaped for inclusion in a URL, you could use Ruby's `uri`, which is a gem included in Ruby's core library, but not implicitly required.

To tell Ruby you want to use it, you could add this at the top of the file:

``` ruby
require 'uri'
```

Then use `URI.encode` on the `font` variable like so:

``` ruby
<link href='https://fonts.googleapis.com/css?family=#{URI.encode(font)}' rel='stylesheet' type='text/css'>
```

**Comment by egillespie** [comment]
Thanks for the tips! I didn't even consider looking for a `pluralize` method. Since this was a Sinatra lesson, is there a way I could have used that Rails helper as a Gem? Or would that only be available to someone going full bore Rails?

I'll start trawling the Ruby API to pick up like things such as `URI.encode` in the future, too.

**Comment by chrisvfritz** [comment]
### Using Rails' `pluralize` method

If you wanted to use Rails' `pluralize` method, they make it (and many other helpers) available in the `actionview` gem, as part of their `TextHelper` module. To use these, you'd first add the gem to your `Gemfile`:

``` ruby
gem 'actionview'
```

Then `require` the gem at at the top of `app.rb`:

``` ruby
require 'action_view'
```

And finally, inside the `class` for your app (again in `app.rb`), add the line:

``` ruby
helpers ActionView::Helpers::TextHelper
```

That tells Sinatra that you want to use the methods in the `ActionView::Helpers::TextHelper` module as helper methods in your views. With it, you gain access to `pluralize` and [all these other helper methods](http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html).

### Learning more Ruby

I don't know if you necessarily need to start trawling the Ruby API. You're certainly free to if you want, but Ruby has a pretty sizeable set of core libraries and it can be kind of daunting. I honestly think just-in-time Googling, paired coding, and code reviews are a pretty decent way to learn more of its ins and outs at a reasonable pace.
